### PR TITLE
fix: enable py 3.12 in ci and fix error in bleu calculation

### PR DESCRIPTION
**Pull request by k4black**
## The problem

`Fraction(..., _normalize=False)` [was removed in python 3.12](https://docs.python.org/3/library/fractions.html#fractions.Fraction) so it causes error in NLTK functions trying to call it this way.

## Changes

* **Enable CI testing for python 3.12**

* **Indicate 3.12 in docs and metadata**

* **Fix BLEU calculation**  
  I have add Child class for Fraction to support `_normalize=False`. Please let me know is better to have functions return `(numerator, denominator)` instead of complex class.

### CODE REVIEW

**Comment by k4black** [comment]
@stevenbird @tomaarsen 
Could you please check this PR?   
As nltk does not forbid it to be installed on 3.12 (officially released a while ago) current version breaks the pipelines and force to use 3.11 version.

**Comment by stevenbird** [comment]
Thanks @k4black !

**Comment by didier-durand** [comment]
Hi, running nltk 3.8.1 on Python 3.12

I get this error when calling sentence_bleu (see code below):

```
File "/Users/didduran/dev/venv/lib/python3.12/site-packages/nltk/translate/bleu_score.py", line 368, in modified_precision
    return Fraction(numerator, denominator, _normalize=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Fraction.__new__() got an unexpected keyword argument '_normalize'
```

Is that related to the above? 

Thanks

Didier

To reproduce:

       ```
        # Define your desired weights (example: higher weight for bi-grams)
        weights = (0.25, 0.25, 0, 0)  # Weights for uni-gram, bi-gram, tri-gram, and 4-gram
        # Reference and predicted texts (same as before)
        reference = [["the", "picture", "is", "clicked", "by", "me"],
                     ["this", "picture", "was", "clicked", "by", "me"]]
        predictions = ["the", "picture", "the", "picture", "by", "me"]
        # Calculate BLEU score with weights
        score = sentence_bleu(reference, predictions, weights=weights)
        print(score)
```

**Comment by purificant** [comment]
You are correct @didier-durand, this is related to the `Fraction` and `_normalize` change in 3.12

**Comment by didier-durand** [comment]
@purificant : thanks for the rapid answer! How can I fix this problem: I already run the latest version of nltk package. v.3.8.1

**Comment by vagetablechicken** [comment]
> @purificant : thanks for the rapid answer! How can I fix this problem: I already run the latest version of nltk package. v.3.8.1

python <= 3.11, I've test on python 3.9, it's ok.

**Comment by abusharaf** [comment]
As per the thread, it's resolved on Python 3.12, but I am not sure why this fix has not been updated on the original package. Do you have any clue? @k4black

**Comment by didier-durand** [comment]
I confirm that it does not work in Python 3.12 on my MacOS (if there is something making it OS-dependent)

**Comment by abusharaf** [comment]
I am not sure to be honest, I don't think it's OS dependent, I believe the update is not reflected on the original source where pip getting the nltk package

**Comment by abusharaf** [comment]
@didier-durand it worked now, thanks for @k4black for updating the file, I looked into this link https://github.com/nltk/nltk/pull/3207/commits/544bf807bf506927872b7b837c6e1514e80419ab#diff-644ebc352f93bb9a63ff8edbc7292e137cf1adaf68d5dc4f1aef13f4de96bf20

and extracted the updates and reflected them on my local bleu_score.py file and it worked very well :),



I think it's matter of only updating the distributed package of NLTK to reflect the updates on bleu_score file

**Comment by didier-durand** [comment]
Thank you for the explanations.
So, will we get a new version of the package with the updated file?

**Comment by abusharaf** [comment]
From your error message earlier this one => ""/Users/didduran/dev/venv/lib/python3.12/site-packages/nltk/translate/bleu_score.py" please open it using MS V Code for instance, and replace it with the content in the link I shared earlier, and rerun your code , it will work perfecto :)

**Comment by didier-durand** [comment]
Yes, I will do that for my laptop. But, my code will included in a project run with DevOps: they recreate full env from official packages at each iteration. So, I will need this fix to get into the official code.

**Comment by kariemoorman** [comment]
I am also receiving this error using Python 3.12. Production build supports Python 3.12 so I cannot revert to version 3.11.  Please can we re-open this request? Thank you.

**Comment by eParkinsonDC** [comment]
error still occuring with nltk==3.8.1 and python 3.12.5

**Comment by ottokruse** [comment]
The fixed code has only been released as a pre-release for now (5 hours ago, someone is working on it!). Pre-releases are ignored by normal pip installs unless you pass the `pre` flag: `pip install --pre nltk`

**Comment by codelion** [comment]
This is fixed in nltk 3.9.1 which is now released.

**Comment by frankiedrake** [comment]
I have Python 3.12.2 and nltk 3.9.1 and still get this error :/
