### ISSUE TITLE
Can't import nltk in Python 3.6 - AttributeError: module 'inspect' has no attribute 'getargspec'

### ISSUE THREAD

**Issue by timjstewart** [nltk/nltk#1541]
I'm running this under Mac OS X in a virtualenv.

$ ipython
Python **3.6.0a0** (default, Sep 24 2015, 09:10:51) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import nltk

AttributeError                            Traceback (most recent call last)
<ipython-input-1-b06499430ee0> in <module>()
----> 1 import nltk

/Users/test/venv/lib/python3.6/site-packages/nltk/__init__.py in <module>()
    113 
    114 from nltk.collocations import *
--> 115 from nltk.decorators import decorator, memoize
    116 from nltk.featstruct import *
    117 from nltk.grammar import *

/Users/test/venv/lib/python3.6/site-packages/nltk/decorators.py in <module>()
    181         return default
    182 
--> 183 @decorator
    184 def memoize(func, *args):
    185     dic = getattr_(func, "memoize_dic", dict)

/Users/test/venv/lib/python3.6/site-packages/nltk/decorators.py in decorator(caller)
    170         dec_func = eval(src, dict(_func_=func, _call_=caller))
    171         return update_wrapper(dec_func, func, infodict)
--> 172     return update_wrapper(_decorator, caller)
    173 
    174 def getattr_(obj, name, default_thunk):

/Users/test/venv/lib/python3.6/site-packages/nltk/decorators.py in update_wrapper(wrapper, model, infodict)
     81 # akin to functools.update_wrapper
     82 def update_wrapper(wrapper, model, infodict=None):
---> 83     infodict = infodict or getinfo(model)
     84     wrapper.__name__ = infodict['name']
     85     wrapper.__doc__ = infodict['doc']

/Users/test/venv/lib/python3.6/site-packages/nltk/decorators.py in getinfo(func)
     57     """
     58     assert inspect.ismethod(func) or inspect.isfunction(func)
---> 59     regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
     60     argnames = list(regargs)
     61     if varargs:

AttributeError: module 'inspect' has no attribute 'getargspec'

**Comment by timjstewart** [comment]
Works fine with python 3.5!  :)

**Comment by alvations** [comment]
Indeed, Python3.6 is another can of worms yet to be handled in `nltk`. Python 3.4 -> 3.5 was quite a headache. Any brave takers to port `nltk` for Py3.6+ ?

A good start would be to read the PEPs on https://docs.python.org/3.6/whatsnew/3.6.html
