### PR TITLE
Properly initialize Portuguese corpus

### LINKED ISSUE #3373: 'PortugueseCategorizedPlaintextCorpusReader' object has no attribute '_fileids'.
The "machado" corpus cannot be used.

Reproduction

```python
!pip install nltk==3.9.1

import nltk

nltk.download("machado")
nltk.download("punkt_tab")

from nltk.corpus import machado

print(machado.fileids())
```

Produces the following error

```
AttributeError                            Traceback (most recent call last)

[<ipython-input-1-c230236cce80>](https://localhost:8080/#) in <cell line: 0>()
      8 from nltk.corpus import machado
      9 
---> 10 print(machado.fileids())

1 frames

[/usr/local/lib/python3.11/dist-packages/nltk/corpus/reader/api.py](https://localhost:8080/#) in fileids(self)
    157         this corpus.
    158         """
--> 159         return self._fileids
    160 
    161     def abspath(self, fileid):

AttributeError: 'PortugueseCategorizedPlaintextCorpusReader' object has no attribute '_fileids'
```

This works with `nltk==3.8`

### PR DESCRIPTION
**Pull request by ekaf**
Fix https://github.com/nltk/nltk/issues/3373: before this PR, the PortugueseCategorizedPlaintextCorpusReader was not properly initialized, due to a mismatch between the class that it inherits from, and the class that it initialized.

### CODE REVIEW

**Comment by ekaf** [comment]
```
from nltk.corpus import machado
print(machado._sent_tokenizer._lang)
```
portuguese

**Comment by stevenbird** [comment]
Thanks @ekaf, @jmccrae.
