### PR TITLE
Fix Stanford interfaces

### PR DESCRIPTION
**Pull request by fievelk**
Related issue: #1584

---

This PR aims to solve the problems we currently experience with Stanford tokenizers and taggers.
We use too many arguments in our classpath, and some of them (i.e. the `slf4j.jar` paths) are breaking current functionalities. This new problem is also related to some changes recently made to the Stanford CoreNLP codebase.

Note: I also took the chance to change some verbosity levels to `False`, as requested in #1509.

### CODE REVIEW

**Comment by fievelk** [comment]
The last changes solved the failures we were experiencing on Jenkins CI. I specified a `CLASSPATH` environment variable for Stanford jars, and I also fixed the `STANFORD_MODELS` variable which was apparently incorrect.
Please let me know if there were some reasons behind the choice of not setting these two variables.

Problems related to the `StanfordNeuralDependencyParser` are currently ignored by this PR. I will open a new issue for them.

I am removing the "work in progress" status.

P.S. As stated in stanfordnlp/CoreNLP#334:
>  In v3.6 [of the Stanford Tagger] you had to have the slf4j logging jars, but we decided that was a big mistake.

I have updated our interfaces so that they work with the latest Stanford release (`v3.7`). This means that they will presumably not work anymore for `v3.6`, since `slf4j.jar` won't be included in the classpath anymore. I think that this is a good solution for the moment, at least until a new and compatible version of `slf4j.jar` is shipped with the Stanford software.

**Comment by stevenbird** [comment]
Thanks @fievelk - this is super helpful
