### PR TITLE
Fix: Saving and loading issues for the PerceptronTagger

### LINKED ISSUE #3379: The save_to_json function for saving a PerceptronTagger doesn't work
## Description
Multiple bugs are present in this function. First of all the `os` library is used but not imported. Also the `os` library is not used correctly as `os.isdir()` doesn't exist and `os.path.isdir()` should be called instead.  Then we attempt to `json.dump` a set. Finally the `TRAINED_TAGGER_PATH` that is checked with said `os` librairy is then **not used** to save the files.

## Steps to Reproduce
Call `PerceptronTagger.save_to_json()` and observe the following traceback:
   
```python
 Traceback (most recent call last):
  File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 28, in <module>
    ptagger.save_to_json(modelname)
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\tag\perceptron.py", line 260, in save_to_json
    assert os.isdir(
           ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?
```

Once `os` is imported and `PerceptronTagger.save_to_json()` is called again observe the following traceback:

```python
Traceback (most recent call last):
  File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 29, in <module>
    ptagger.save_to_json(modelname)
  File "c:\Users\TFerrari\Desktop\nltk_push\perceptron2.py", line 261, in save_to_json
    assert os.isdir(
           ^^^^^^^^
AttributeError: module 'os' has no attribute 'isdir'. Did you mean: 'chdir'?
```

After a quick fix call  `PerceptronTagger.save_to_json()` again and observe the following traceback:

```python
Traceback (most recent call last):
  File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 29, in <module>
    ptagger.save_to_json(modelname)
  File "c:\Users\TFerrari\Desktop\nltk_push\perceptron2.py", line 270, in save_to_json
    json.dump(self.classes, fout)
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
```

Finally, when everything works, the files are saved correctly but are not saved in the `TRAINED_TAGGER_PATH` that is checked by the assert.

## Cause

These errors were introduced in #3270 

https://github.com/nltk/nltk/blob/0753ee5bb0096b4a4b3dd587e784ce07e7f34dab/nltk/tag/perceptron.py#L258-L269

`os` is not imported at the start of the file and `assert os.isdir(TRAINED_TAGGER_PATH), f"Path set for saving needs to be a directory"` should be         `assert os.path.isdir(TRAINED_TAGGER_PATH), f"Path set for saving needs to be a directory"`

We try to `json.dump()` a set which is not possible. Allowing the dump to default to a list fixes the problem.

```python
with open(loc + TAGGER_JSONS[lang]["classes"], "w") as fout: 
     json.dump(self.classes, fout, default=list) 
```

`TRAINED_TAGGER_PATH` is then not used to save the model which is saved and the `loc` location when it should be saved at the `TRAINED_TAGGER_PATH\loc` location.

```python
 with open(loc + TAGGER_JSONS[lang]["weights"], "w") as fout: 
     json.dump(self.model.weights, fout) 
 with open(loc + TAGGER_JSONS[lang]["tagdict"], "w") as fout: 
     json.dump(self.tagdict, fout) 
 with open(loc + TAGGER_JSONS[lang]["classes"], "w") as fout: 
     json.dump(self.classes, fout, default=list)
```

should be

```python
with open(TRAINED_TAGGER_PATH + loc + TAGGER_JSONS[lang]["weights"], "w") as fout: 
   json.dump(self.model.weights, fout) 
with open(TRAINED_TAGGER_PATH + loc + TAGGER_JSONS[lang]["tagdict"], "w") as fout: 
   json.dump(self.tagdict, fout) 
with open(TRAINED_TAGGER_PATH + loc + TAGGER_JSONS[lang]["classes"], "w") as fout: 
   json.dump(self.classes, fout, default=list) 
```

### LINKED ISSUE #3380: Saving a PerceptronTagger from the train function doesn't work
## Description
When attempting to save a model using the `save_loc` parameter in `PerceptronTagger.train()`, an error occurs due to an undefined variable `loc`. Instead of `loc`, the function should be passing `save_loc` to `self.save_to_json`.

## Steps to Reproduce
Call `PerceptronTagger.train()` with `save_loc` specified and observe the following traceback:

   
```python
   Traceback (most recent call last):
     File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 26, in <module>
       ptagger.train(train_corpus.tagged_sents(), save_loc=modelname, nr_iter=1)
     File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\tag\perceptron.py", line 256, in train
       self.save_to_json(loc)
                         ^^^
   NameError: name 'loc' is not defined
```

## Cause

This error was introduced in #3270 

https://github.com/nltk/nltk/blob/0753ee5bb0096b4a4b3dd587e784ce07e7f34dab/nltk/tag/perceptron.py#L254-L256

Here, `loc` is not defined, and `save_loc` should be used instead.

### PR DESCRIPTION
**Pull request by LordTT**
See issues https://github.com/nltk/nltk/issues/3379 and https://github.com/nltk/nltk/issues/3380 for an in-detail explanation of the bugs

Basically the saving and loading functions for the PerceptronTagger don't work correctly and a few simple fixes solve that.

Most of the explanations are in the issues. I also simplified the `load_from_json` function so the user simply uses the same `loc` as in the `save_to_json`

Finally I am not sure about the usage of `TRAINED_TAGGER_PATH` but I don't want to modify too much how the functions are intended to work.

fixes #3379 fixes #3380

### CODE REVIEW

**Review by ekaf — CHANGES_REQUESTED** [review]
I don't understand the need to define both _self.classes_ and _self.model.classes_ in the PerceptronTagger class, to denote the same thing (L. 280). And the purpose of _PerceptronTagger.encode_json_object()_ is probably to call it before saving. Any suggestion, @alvations?

It would be good to have the model saving tested in the existing doctest for the class. Specifying a location in the call to _tagger.train()_ allows this. Unfortunately, trying that from your commit produces errors, so this PR would need more work. Also, you forgot to re-commit the _perceptron.py_ file after it was changed by 'black', and that's the reason why CI fails.

@LordTT, it is commendable when you write that you don't want to modify too much. On the other hand, this might  be a good opportunity to clean up in this old code. For ex. the \_get_pretrain_model()_ function is not usable, because it tries to load files that don't exist, while referring to Penn treebank sections.
