### PR TITLE
Fix saving PerceptronTagger

### LINKED ISSUE #3379: The save_to_json function for saving a PerceptronTagger doesn't work
## Description
Multiple bugs are present in this function. First of all the `os` library is used but not imported. Also the `os` library is not used correctly as `os.isdir()` doesn't exist and `os.path.isdir()` should be called instead.  Then we attempt to `json.dump` a set. Finally the `TRAINED_TAGGER_PATH` that is checked with said `os` librairy is then **not used** to save the files.

## Steps to Reproduce
Call `PerceptronTagger.save_to_json()` and observe the following traceback:
   
```python
 Traceback (most recent call last):
  File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 28, in <module>
    ptagger.save_to_json(modelname)
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\tag\perceptron.py", line 260, in save_to_json
    assert os.isdir(
           ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?
```

Once `os` is imported and `PerceptronTagger.save_to_json()` is called again observe the following traceback:

```python
Traceback (most recent call last):
  File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 29, in <module>
    ptagger.save_to_json(modelname)
  File "c:\Users\TFerrari\Desktop\nltk_push\perceptron2.py", line 261, in save_to_json
    assert os.isdir(
           ^^^^^^^^
AttributeError: module 'os' has no attribute 'isdir'. Did you mean: 'chdir'?
```

After a quick fix call  `PerceptronTagger.save_to_json()` again and observe the following traceback:

```python
Traceback (most recent call last):
  File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 29, in <module>
    ptagger.save_to_json(modelname)
  File "c:\Users\TFerrari\Desktop\nltk_push\perceptron2.py", line 270, in save_to_json
    json.dump(self.classes, fout)
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
```

Finally, when everything works, the files are saved correctly but are not saved in the `TRAINED_TAGGER_PATH` that is checked by the assert.

## Cause

These errors were introduced in #3270 

https://github.com/nltk/nltk/blob/0753ee5bb0096b4a4b3dd587e784ce07e7f34dab/nltk/tag/perceptron.py#L258-L269

`os` is not imported at the start of the file and `assert os.isdir(TRAINED_TAGGER_PATH), f"Path set for saving needs to be a directory"` should be         `assert os.path.isdir(TRAINED_TAGGER_PATH), f"Path set for saving needs to be a directory"`

We try to `json.dump()` a set which is not possible. Allowing the dump to default to a list fixes the problem.

```python
with open(loc + TAGGER_JSONS[lang]["classes"], "w") as fout: 
     json.dump(self.classes, fout, default=list) 
```

`TRAINED_TAGGER_PATH` is then not used to save the model which is saved and the `loc` location when it should be saved at the `TRAINED_TAGGER_PATH\loc` location.

```python
 with open(loc + TAGGER_JSONS[lang]["weights"], "w") as fout: 
     json.dump(self.model.weights, fout) 
 with open(loc + TAGGER_JSONS[lang]["tagdict"], "w") as fout: 
     json.dump(self.tagdict, fout) 
 with open(loc + TAGGER_JSONS[lang]["classes"], "w") as fout: 
     json.dump(self.classes, fout, default=list)
```

should be

```python
with open(TRAINED_TAGGER_PATH + loc + TAGGER_JSONS[lang]["weights"], "w") as fout: 
   json.dump(self.model.weights, fout) 
with open(TRAINED_TAGGER_PATH + loc + TAGGER_JSONS[lang]["tagdict"], "w") as fout: 
   json.dump(self.tagdict, fout) 
with open(TRAINED_TAGGER_PATH + loc + TAGGER_JSONS[lang]["classes"], "w") as fout: 
   json.dump(self.classes, fout, default=list) 
```

### LINKED ISSUE #3380: Saving a PerceptronTagger from the train function doesn't work
## Description
When attempting to save a model using the `save_loc` parameter in `PerceptronTagger.train()`, an error occurs due to an undefined variable `loc`. Instead of `loc`, the function should be passing `save_loc` to `self.save_to_json`.

## Steps to Reproduce
Call `PerceptronTagger.train()` with `save_loc` specified and observe the following traceback:

   
```python
   Traceback (most recent call last):
     File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 26, in <module>
       ptagger.train(train_corpus.tagged_sents(), save_loc=modelname, nr_iter=1)
     File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\tag\perceptron.py", line 256, in train
       self.save_to_json(loc)
                         ^^^
   NameError: name 'loc' is not defined
```

## Cause

This error was introduced in #3270 

https://github.com/nltk/nltk/blob/0753ee5bb0096b4a4b3dd587e784ce07e7f34dab/nltk/tag/perceptron.py#L254-L256

Here, `loc` is not defined, and `save_loc` should be used instead.

### PR DESCRIPTION
**Pull request by ekaf**
Fix #3379 and #3380. This is a more comprehensive alternative to #3381, with additional code cleanup. 
This PR also tests the _save_to_json_ functionality , by specifying a _save_loc_ in the call to _train_ from the doctest in the PerceptronTagger class, and saves the trained tagger in the _tempfile.gettempdir()_ directory. 
Also, the _jsontags_ encode/decode mechanism is now used when loading and saving.
A little more code cleanup could be considered, since there is no obvious need to define both _self.classes_ and _self.model.classes_ to denote the same thing in the PerceptronTagger class. I nevertheless chose not to change that, since it goes way back and would  break old code.

### CODE REVIEW

**Comment by LordTT** [comment]
Thanks for fixing this ! Sadly I didn't have the time to finish myself.

**Comment by ekaf** [comment]
Thanks for raising the issues @LordTT!  Reporting the problems with a convincing description is the most important.

File: nltk/tag/perceptron.py [hunk 1]
```diff
@@ -381,17 +361,19 @@ def _load_data_conll_format(filename):
         return sentences
 
 
-def _get_pretrain_model():
```
Comment (stevenbird) [inline nltk/tag/perceptron.py:384]: FYI It's a convention used across NLTK to provide demonstration functionality when the module is called on the command line.

Comment (ekaf) [reply nltk/tag/perceptron.py:384]: Thanks @stevenbird, the added demo functionality seems quite useful.

**Comment by stevenbird** [comment]
Thanks @ekaf!
