### ISSUE TITLE
Dispersion Plot has an incorrectly used Parameter

### ISSUE THREAD

**Issue by ruffyleaf** [nltk/nltk#1315]
`nltk.draw.dispersion.dispersion_plot(text, words, ignore_case=False, title='Lexical Dispersion Plot')[source]¶
`
'title' is seen to be a parameter in the source code and above(documentation), but we cannot modify this parameter.

**Comment by lrnzcig** [comment]
Hi @ruffyleaf, this is working for me with no problem. Could you please post the code you are using in your call? Thanks.

**Comment by ruffyleaf** [comment]
Hey @lrnzcig, I used nltk.**version** '3.0.2', Python 2.7.10, Anaconda 2.2.0

```
nltk.draw.dispersion.dispersion_plot(txt, words, title="Test")
```

And I got the error:
`TypeError: dispersion_plot() got an unexpected keyword argument 'title'`

**Comment by lrnzcig** [comment]
@ruffyleaf You're right, I've checked for python 2.7 and nltk version 3.0.2, and the method `dispersion_plot` does not accept the argument `title`; the title is always set to "Lexical Dispersion Plot". I'd suggest you upgrade to version nltk version 3.1 (using the command `conda upgrade nltk`). Cheers.

**Comment by stevenbird** [comment]
Thanks @lrnzcig

**Comment by ruffyleaf** [comment]
Thanks @lrnzcig. I thought I was at the latest version because the Docs said "Version 3.0 Documentation". Have since updated to 3.1 and works. :+1:
