### ISSUE TITLE
nltk.text.demo() fails in py3.x

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#942]
In py3.x, dispersion plot is failing:

```
alvas@ubi:~$ python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.text.demo()
<Text: The Fulton County Grand Jury said Friday an...>

Concordance:
Displaying 14 of 14 matches:
altimore's Florida Grapefruit League news ripened considerably late today when
. The appointment was announced at a news conference at which Skorich said he 
 who will be the unhappiest over the news that Musial probably will sit out mo
ts win a dramatic pennant . Romantic news concerns Mrs. Joan Monroe Armour and
entific training , he added . `` The news of their experiments reaches the far
resented in the averages . Some good news Although it looked like a routine te
ters it was accompanied by some good news . A substantial rise in new orders a
 New York Social Register which made news last week . Published annually by Wi
ut to President Kennedy at his first news conference last January was about hi
ead as an exaggeration ( see foreign news ) , and the U.S. was agreeing with i
 to his private office and broke the news : he would lead the fight to oust Co
to regard as `` an inferior man '' . News of Rayburn's commitment soon leaked 
 moment . In 1920 , as the startling news that the 1919 White Sox had conspire
embles . Soon after Loper leaked the news that Frankie had ordered `` two of e

Distributionally similar words:
president charge prices work impression movement result return
committee statement army government suggestion time reports state
season bureau driveway fact

Collocations:
per cent; New York; United States; White House; home runs; last week;
San Francisco; last year; Los Angeles; anti-trust laws; Premier
Khrushchev; Kansas City; President Kennedy; years ago; Air Force;
United Nations; New Orleans; High School; Viet Nam; collective
bargaining

Dispersion plot:
/usr/local/lib/python3.4/dist-packages/nltk/draw/__init__.py:15: UserWarning: nltk.draw package not loaded (please install Tkinter library).
  warnings.warn("nltk.draw package not loaded "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/nltk/text.py", line 593, in demo
    text.dispersion_plot(['news', 'report', 'said', 'announced'])
  File "/usr/local/lib/python3.4/dist-packages/nltk/text.py", line 444, in dispersion_plot
    from nltk.draw import dispersion_plot
ImportError: cannot import name 'dispersion_plot'
```

It's working in py2.7 though, in `python 2.7+`, the dispersion and libplots pops up:

```
alvas@ubi:~$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.text.demo()
<Text: The Fulton County Grand Jury said Friday an...>

Concordance:
Displaying 14 of 14 matches:
altimore's Florida Grapefruit League news ripened considerably late today when
. The appointment was announced at a news conference at which Skorich said he 
 who will be the unhappiest over the news that Musial probably will sit out mo
ts win a dramatic pennant . Romantic news concerns Mrs. Joan Monroe Armour and
entific training , he added . `` The news of their experiments reaches the far
resented in the averages . Some good news Although it looked like a routine te
ters it was accompanied by some good news . A substantial rise in new orders a
 New York Social Register which made news last week . Published annually by Wi
ut to President Kennedy at his first news conference last January was about hi
ead as an exaggeration ( see foreign news ) , and the U.S. was agreeing with i
 to his private office and broke the news : he would lead the fight to oust Co
to regard as `` an inferior man '' . News of Rayburn's commitment soon leaked 
 moment . In 1920 , as the startling news that the 1919 White Sox had conspire
embles . Soon after Loper leaked the news that Frankie had ordered `` two of e

Distributionally similar words:
charge advantage movement reports suggestion army work president
committee return statement season driveway impression hope result best
state bureau prices

Collocations:
per cent; New York; United States; White House; home runs; last week;
San Francisco; last year; Los Angeles; anti-trust laws; Premier
Khrushchev; Kansas City; President Kennedy; years ago; Air Force;
United Nations; New Orleans; High School; Viet Nam; collective
bargaining

Dispersion plot:

Vocabulary plot:

Indexing:
text[3]: Grand
text[3:5]: [u'Grand', u'Jury']
text.vocab()['news']: 13
```

Related question (not really an issue): http://stackoverflow.com/questions/29514778/nltk-text-throws-an-error

**Comment by stevenbird** [comment]
@alvations do you have Tkinter installed for Python 3.4?

NB https://github.com/nltk/nltk/blob/develop/nltk/draw/__init__.py#L15

(Strangely, the second line of the warning message is not appearing in your output.)

**Comment by alvations** [comment]
After installing tkinter, GTK and cairo still has issues with py3.x. 

```
alvas@ubi:~$ python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import nltk
>>> nltk.text.demo()
<Text: The Fulton County Grand Jury said Friday an...>

Concordance:
Displaying 14 of 14 matches:
altimore's Florida Grapefruit League news ripened considerably late today when
. The appointment was announced at a news conference at which Skorich said he 
 who will be the unhappiest over the news that Musial probably will sit out mo
ts win a dramatic pennant . Romantic news concerns Mrs. Joan Monroe Armour and
entific training , he added . `` The news of their experiments reaches the far
resented in the averages . Some good news Although it looked like a routine te
ters it was accompanied by some good news . A substantial rise in new orders a
 New York Social Register which made news last week . Published annually by Wi
ut to President Kennedy at his first news conference last January was about hi
ead as an exaggeration ( see foreign news ) , and the U.S. was agreeing with i
 to his private office and broke the news : he would lead the fight to oust Co
to regard as `` an inferior man '' . News of Rayburn's commitment soon leaked 
 moment . In 1920 , as the startling news that the 1919 White Sox had conspire
embles . Soon after Loper leaked the news that Frankie had ordered `` two of e

Distributionally similar words:
government work prices opinion president state result announcement
suggestion hope return movement season fact driveway committee charge
impression bureau reports

Collocations:
per cent; New York; United States; White House; home runs; last week;
San Francisco; last year; Los Angeles; anti-trust laws; Premier
Khrushchev; Kansas City; President Kennedy; years ago; Air Force;
United Nations; New Orleans; High School; Viet Nam; collective
bargaining

Dispersion plot:
/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py:18: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3.py:215: Warning: Source ID 7 was not found when attempting to remove it
  GLib.source_remove(self._idle_event_id)

Vocabulary plot:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3.py:215: Warning: Source ID 535 was not found when attempting to remove it
  GLib.source_remove(self._idle_event_id)

Indexing:
text[3]: Grand
text[3:5]: ['Grand', 'Jury']
text.vocab()['news']: 13
```

I'll try to update my pips and then install `cairocffi` to see whether it works

**Comment by alvations** [comment]
After installing `tkinter` on py3.x. There were dependencies missing. I managed to resolve them by installing `libffi`, `libffi-dev` and then `cairocffi`

On Ubuntu, these line resolves the dispersion and vocab problem in `nltk.text.demo()`:

```
$ apt-get install python3-tk
$ apt-get install libffi6 libffi-dev
$ pip3 install cairocffi
```

But it still gives a warning:

```
Dispersion plot:
/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3.py:215: Warning: Source ID 7 was not found when attempting to remove it
  GLib.source_remove(self._idle_event_id)

Vocabulary plot:
/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3.py:215: Warning: Source ID 126 was not found when attempting to remove it
  GLib.source_remove(self._idle_event_id)
```

**Comment by stevenbird** [comment]
Thanks for the update @alvations. Unfortunately I can't reproduce any of this with my Python 3.4 kit on Mac OSX.

**Comment by alvations** [comment]
@stevenbird , the GTK had some problems in unix, i think it should resolve itself in the next stable update: http://stackoverflow.com/questions/29540845/how-can-i-deactivate-warning-source-id-510-was-not-found-when-attempting-to-re. I guess that's a close for this problem =)

**Comment by stevenbird** [comment]
Thanks for documenting all this @alvations. I'm going to close this since I don't think there's anything to do on the NLTK side.
