### ISSUE TITLE
Syntax error when importing NLTK

### ISSUE THREAD

**Issue by Commiccannon** [nltk/nltk#2533]
I have just installed NLTK via pip onto a new device it was working perfectly on my raspberry pi however when i try to import it i get this error
`Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import nltk
  File "C:\Python27\lib\site-packages\nltk\__init__.py", line 128, in <module>
    from nltk.collocations import *
  File "C:\Python27\lib\site-packages\nltk\collocations.py", line 35, in <module>
    from nltk.probability import FreqDist
  File "C:\Python27\lib\site-packages\nltk\probability.py", line 333
    print("%*s" % (width, samples[i]), end=" ")
                                          ^
SyntaxError: invalid syntax`
Any help would be greatly appreciated

**Comment by stevenbird** [comment]
NLTK no longer works with Python 2.7

**Comment by ozgurgundogan** [comment]
Can we install previous releases ? some of our old projects written on Python2.7 and using NLTK ?

**Comment by stevenbird** [comment]
Please use a previous release

**Comment by hmkim** [comment]
What version is exist compatible with Python2.7?

**Comment by hmkim** [comment]
> Please use a previous release

What version is exist compatible with Python2.7?

**Comment by hmkim** [comment]
oh, I see.

`pip install nltk==3.0`

**Comment by Liza23** [comment]
Even after this I keep an error which is this:
`Traceback (most recent call last):
  File "lda_model.py", line 14, in <module>
    import preprocess_data
  File "/home/liza/Desktop/Food-CV-HCI/Transformed LDA/DF-LDA-0.1.2/example/preprocess_data.py", line 8, in <module>
    from nltk.stem import WordNetLemmatizer, SnowballStemmer
  File "/home/liza/.local/lib/python2.7/site-packages/nltk/__init__.py", line 103, in <module>
    from nltk.collocations import *
  File "/home/liza/.local/lib/python2.7/site-packages/nltk/collocations.py", line 37, in <module>
    from nltk.probability import FreqDist
  File "/home/liza/.local/lib/python2.7/site-packages/nltk/probability.py", line 47, in <module>
    from collections import defaultdict
  File "/home/liza/.local/lib/python2.7/site-packages/nltk/collections.py", line 13, in <module>
    from collections import defaultdict, deque, Counter
ImportError: cannot import name defaultdict
`
Can someone help why this might be happening?
