### ISSUE TITLE
Difference between stanford-corenlp-full-2018-02-27  and stanford-corenlp-full-2018-10-05

### ISSUE THREAD

**Issue by limengmingx** [nltk/nltk#2301]
when I follow the tutorial on `pos_tagger = CoreNLPParser(url='http://localhost:9000', tagtype='pos')` with `stanford-corenlp-full-2018-10-05 package`, I got an error:

`TypeError: __init__() got an unexpected keyword argument 'tagtype'`

The error was solved when I choosing the` stanford-corenlp-full-2018-02-27`. so I think there maybe something wrong for the latest released package.

**Comment by alvations** [comment]
Which version of NLTK are you using? Try `pip install -U nltk` =)

The `tagtype` is introduced after https://github.com/nltk/nltk/commit/b974b6156813246ccb25ba85b8aa70ae5e4fb0d8#diff-bae6ec94fc0cc6068b278a716f9bb95e

**Comment by limengmingx** [comment]
With the command `pip install -U nltk`, Both packages works fine. Thanks !
