### ISSUE TITLE
The save_to_json function for saving a PerceptronTagger doesn't work

### ISSUE THREAD

**Issue by LordTT** [nltk/nltk#3379]
## Description
Multiple bugs are present in this function. First of all the `os` library is used but not imported. Also the `os` library is not used correctly as `os.isdir()` doesn't exist and `os.path.isdir()` should be called instead.  Then we attempt to `json.dump` a set. Finally the `TRAINED_TAGGER_PATH` that is checked with said `os` librairy is then **not used** to save the files.

## Steps to Reproduce
Call `PerceptronTagger.save_to_json()` and observe the following traceback:
   
```python
 Traceback (most recent call last):
  File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 28, in <module>
    ptagger.save_to_json(modelname)
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\site-packages\nltk\tag\perceptron.py", line 260, in save_to_json
    assert os.isdir(
           ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?
```

Once `os` is imported and `PerceptronTagger.save_to_json()` is called again observe the following traceback:

```python
Traceback (most recent call last):
  File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 29, in <module>
    ptagger.save_to_json(modelname)
  File "c:\Users\TFerrari\Desktop\nltk_push\perceptron2.py", line 261, in save_to_json
    assert os.isdir(
           ^^^^^^^^
AttributeError: module 'os' has no attribute 'isdir'. Did you mean: 'chdir'?
```

After a quick fix call  `PerceptronTagger.save_to_json()` again and observe the following traceback:

```python
Traceback (most recent call last):
  File "c:\Users\TFerrari\Desktop\nltk_push\nltk_reproduce.py", line 29, in <module>
    ptagger.save_to_json(modelname)
  File "c:\Users\TFerrari\Desktop\nltk_push\perceptron2.py", line 270, in save_to_json
    json.dump(self.classes, fout)
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\TFerrari\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
```

Finally, when everything works, the files are saved correctly but are not saved in the `TRAINED_TAGGER_PATH` that is checked by the assert.

## Cause

These errors were introduced in #3270 

https://github.com/nltk/nltk/blob/0753ee5bb0096b4a4b3dd587e784ce07e7f34dab/nltk/tag/perceptron.py#L258-L269

`os` is not imported at the start of the file and `assert os.isdir(TRAINED_TAGGER_PATH), f"Path set for saving needs to be a directory"` should be         `assert os.path.isdir(TRAINED_TAGGER_PATH), f"Path set for saving needs to be a directory"`

We try to `json.dump()` a set which is not possible. Allowing the dump to default to a list fixes the problem.

```python
with open(loc + TAGGER_JSONS[lang]["classes"], "w") as fout: 
     json.dump(self.classes, fout, default=list) 
```

`TRAINED_TAGGER_PATH` is then not used to save the model which is saved and the `loc` location when it should be saved at the `TRAINED_TAGGER_PATH\loc` location.

```python
 with open(loc + TAGGER_JSONS[lang]["weights"], "w") as fout: 
     json.dump(self.model.weights, fout) 
 with open(loc + TAGGER_JSONS[lang]["tagdict"], "w") as fout: 
     json.dump(self.tagdict, fout) 
 with open(loc + TAGGER_JSONS[lang]["classes"], "w") as fout: 
     json.dump(self.classes, fout, default=list)
```

should be

```python
with open(TRAINED_TAGGER_PATH + loc + TAGGER_JSONS[lang]["weights"], "w") as fout: 
   json.dump(self.model.weights, fout) 
with open(TRAINED_TAGGER_PATH + loc + TAGGER_JSONS[lang]["tagdict"], "w") as fout: 
   json.dump(self.tagdict, fout) 
with open(TRAINED_TAGGER_PATH + loc + TAGGER_JSONS[lang]["classes"], "w") as fout: 
   json.dump(self.classes, fout, default=list) 
```
