### ISSUE TITLE
Character encoding in Toolbox corpus reader

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#507]
The following works fine in 2.7 but breaks in 3.2:

> > > from nltk.corpus import toolbox
> > > toolbox.words('rotokas.dic')
> > >   ...
> > >   File ".../python3.2/site-packages/nltk-3.0a2-py3.2.egg/nltk/toolbox.py", line 120, in fields
> > >     val = val.decode(encoding, errors)
> > > AttributeError: 'str' object has no attribute 'decode'

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/1f7db91e834041fdd66e06812a59efa75de87993
