### ISSUE TITLE
'PortugueseCategorizedPlaintextCorpusReader' object has no attribute '_fileids'.

### ISSUE THREAD

**Issue by jmccrae** [nltk/nltk#3373]
The "machado" corpus cannot be used.

Reproduction

```python
!pip install nltk==3.9.1

import nltk

nltk.download("machado")
nltk.download("punkt_tab")

from nltk.corpus import machado

print(machado.fileids())
```

Produces the following error

```
AttributeError                            Traceback (most recent call last)

[<ipython-input-1-c230236cce80>](https://localhost:8080/#) in <cell line: 0>()
      8 from nltk.corpus import machado
      9 
---> 10 print(machado.fileids())

1 frames

[/usr/local/lib/python3.11/dist-packages/nltk/corpus/reader/api.py](https://localhost:8080/#) in fileids(self)
    157         this corpus.
    158         """
--> 159         return self._fileids
    160 
    161     def abspath(self, fileid):

AttributeError: 'PortugueseCategorizedPlaintextCorpusReader' object has no attribute '_fileids'
```

This works with `nltk==3.8`

**Comment by ekaf** [comment]
Many other methods of this class (for ex. _citation, license, readme, root_) are also raising the same kind of error. It seems there must be something wrong with the class initialization. I looked in NLTK's _git log_, but have not yet found any commit from the recent years, that could explain this change. Could it be a change in Python itself?
In that case, other corpora might also be affected.
@jmccrae, please don't hesitate to share any idea that could contribute towards a solution.

**Comment by jmccrae** [comment]
I would assume there is an error in loading the corpus. I think the issue may be that the files within the corpus are compressed with `gzip` but have filenames like `teatro/matt01.txt` not `teatro/matt01.txt.gz` so perhaps NLTK is loading them as plain text and then failing because they are not valid Latin-1 encoded files?

**Comment by ekaf** [comment]
Thanks @jmccrae, zipfiles have often been the culprit in NLTK's data issues. But the problem here is due to [this commit](https://github.com/nltk/nltk/pull/3283/commits/f2054c7441edcb46e162fba8d7a7e75c845083a0) last summer, where I accidentally deleted a line from the class initialization.
