### ISSUE TITLE
hmm_treebank_pos_tagger model is broken

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#428]
See https://github.com/nltk/nltk/commit/a3e492b35ec309b2ba171920da53b823171f21e3#commitcomment-3580472

In NLTK master loading this model raises the following exception:

```
----> 1 nltk.data.load('taggers/hmm_treebank_pos_tagger/treebank.tagger.pickle.gz')

/Users/kmike/svn/nltk/nltk/data.pyc in load(resource_url, format, cache, verbose, logic_parser, fstruct_parser, encoding)
    628         resource_val = opened_resource.read()
    629     elif format == 'pickle':
--> 630         resource_val = pickle.load(opened_resource)
    631     elif format == 'yaml':
    632         import yaml

AttributeError: 'module' object has no attribute 'IdentityTransform'
```

It looks like this model was broken long time ago. It didn't load before https://github.com/nltk/nltk/commit/a3e492b35ec309b2ba171920da53b823171f21e3 with an another exception: 

```
----> 1 nltk.data.load('taggers/hmm_treebank_pos_tagger/treebank.tagger.pickle.gz')

/Users/kmike/svn/nltk/nltk/data.pyc in load(resource_url, format, cache, verbose, logic_parser, fstruct_parser, encoding)
    628         resource_val = opened_resource.read()
    629     elif format == 'pickle':
--> 630         resource_val = pickle.load(opened_resource)
    631     elif format == 'yaml':
    632         import yaml

/Users/kmike/envs/nltk/lib/python2.7/copy_reg.pyc in _reconstructor(cls, base, state)
     46 def _reconstructor(cls, base, state):
     47     if base is object:
---> 48         obj = object.__new__(cls)
     49     else:
     50         obj = base.__new__(cls, state)

TypeError: ('object.__new__(ConditionalProbDist) is not safe, use dict.__new__()', <function _reconstructor at 0x10107bc80>, (<class 'nltk.probability.ConditionalProbDist'>, <type 'object'>, None))
```

I tracked this down - error is caused by https://github.com/nltk/nltk/commit/7ab305d12f379cf4e3cb7720ffb214022f1b620a. But before https://github.com/nltk/nltk/commit/7ab305d12f379cf4e3cb7720ffb214022f1b620a the model also didn't load, with an another exception:

```
In [1]: import nltk

In [2]: nltk.data.load('taggers/hmm_treebank_pos_tagger/treebank.tagger.pickle.gz')
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-4a62f6801e80> in <module>()
----> 1 nltk.data.load('taggers/hmm_treebank_pos_tagger/treebank.tagger.pickle.gz')

/Users/kmike/svn/nltk/nltk/data.pyc in load(resource_url, format, cache, verbose, logic_parser, fstruct_parser)
    592     # Load the resource.
    593     if format == 'pickle':
--> 594         resource_val = pickle.load(_open(resource_url))
    595     elif format == 'yaml':
    596         import yaml

ImportError: No module named nltk_contrib.coref.util
```

I think at this point is could be better to re-train this model to avoid all these issues (and unicode issue as well). It could become a problem for older NLTK versions (with nltk_contrib installed), so an another data index for NLTK3 is welcome :) Alternatively, we could decide that this model is not important enough (it was broken for a long time and nobody complained + there is no tests for it) and either remove it or re-train without providing compatibility for older NLTKs.

**Comment by stevenbird** [comment]
@kmike thanks for the analysis, including the history. It looks like we can safely remove the hmm_treebank_pos_tagger model.
