### ISSUE TITLE
AttributeError for Rule object in Python3.4

### ISSUE THREAD

**Issue by japerk** [nltk/nltk#769]
The following code works perfectly with Python3.3 but produces an error with Python3.4, at least on Mac OS X. I've included the error output below the code. I've looked at the code for rule.py, and it's in a try-except block, but Python3.4 doesn't seem to care about that.

> from nltk.corpus import treebank
> from nltk.tag import UnigramTagger, brill, brill_trainer
> from nltk.tbl import Template
> train_sents = treebank.tagged_sents()[:3000]
> tagger = UnigramTagger(train_sents)
> trainer = brill_trainer.BrillTaggerTrainer(tagger, [brill.Template(brill.Pos([-1]))])
> brill_tagger = trainer.train(train_sents)

Traceback (most recent call last):
  File "/Users/jacob/py34env/lib/python3.4/site-packages/nltk/tbl/rule.py", line 191, in **hash**
    return self.__hash
AttributeError: 'Rule' object has no attribute '_Rule__hash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jacob/py34env/lib/python3.4/site-packages/nltk/tbl/rule.py", line 200, in **repr**
    return self.__repr
AttributeError: 'Rule' object has no attribute '_Rule__repr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jacob/py34env/lib/python3.4/site-packages/nltk/tag/brill_trainer.py", line 288, in train
    self._init_mappings(test_sents, train_sents)
  File "/Users/jacob/py34env/lib/python3.4/site-packages/nltk/tag/brill_trainer.py", line 359, in _init_mappings
    train_sents)
  File "/Users/jacob/py34env/lib/python3.4/site-packages/nltk/tag/brill_trainer.py", line 387, in _update_rule_applies
    if pos in self._positions_by_rule[rule]:
  File "/Users/jacob/py34env/lib/python3.4/site-packages/nltk/tbl/rule.py", line 193, in __hash__
    self.**hash = hash(repr(self))
  File "/Users/jacob/py34env/lib/python3.4/site-packages/nltk/tbl/rule.py", line 210, in __repr**
    ", ".join("({0:s},{1:s})".format(f,unicode_repr(v)) for (f,v) in self._conditions)))
  File "/Users/jacob/py34env/lib/python3.4/site-packages/nltk/tbl/rule.py", line 210, in <genexpr>
    ", ".join("({0:s},{1:s})".format(f,unicode_repr(v)) for (f,v) in self._conditions)))
TypeError: non-empty format string passed to object.__format__

**Comment by edran** [comment]
Confirmed on Ubuntu 12.04 and NLTK v3.0.0.

It appears only in Python 3.4 because the change was introduced in that version. It should have issued a warning in 3.2+ (source: http://bugs.python.org/issue7994)

**Comment by edran** [comment]
It actually looks like the issue has been solved in bffbaee.

**Comment by dimazest** [comment]
@japerk is there a test that checks this scenario?

There is one failing test in the develop branch. Once failing tests are fixed (i'm working on it), we can hook up a CI test for every pull request.

**Comment by japerk** [comment]
I don't have a specific test, but it seems that anything that exercises BrillTaggerTrainer.train would do it.

**Comment by alvations** [comment]
On Python 2.7 and 3.6:

```
~/git-stuff/nltk-py36/nltk$ python2.7
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk.corpus import treebank

>>> 
>>> from nltk.tag import UnigramTagger, brill, brill_trainer
>>> from nltk.tbl import Template
>>> train_sents = treebank.tagged_sents()[:3000]
>>> tagger = UnigramTagger(train_sents)
>>> trainer = brill_trainer.BrillTaggerTrainer(tagger, [brill.Template(brill.Pos([-1]))])
>>> brill_tagger = trainer.train(train_sents)
>>> brill_tagger.tag('This is a foo bar sentence'.split())
[('This', u'DT'), ('is', u'VBZ'), ('a', u'DT'), ('foo', None), ('bar', u'NN'), ('sentence', None)]

~/git-stuff/nltk-py36/nltk$ python3
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk.corpus import treebank
>>> from nltk.tag import UnigramTagger, brill, brill_trainer
>>> from nltk.tbl import Template
>>> train_sents = treebank.tagged_sents()[:3000]
>>> tagger = UnigramTagger(train_sents)
>>> trainer = brill_trainer.BrillTaggerTrainer(tagger, [brill.Template(brill.Pos([-1]))])
>>> brill_tagger = trainer.train(train_sents)
>>> brill_tagger.tag('This is a foo bar sentence'.split())
[('This', 'DT'), ('is', 'VBZ'), ('a', 'DT'), ('foo', None), ('bar', 'NN'), ('sentence', None)]
```

@stevenbird maybe dropping support for Python 3.4 would be good. We could still keep 2.7, 3.5 and push for 3.6 support.
